# Model parameters:
model:
  encoder_name: resnet18
  head_base_heatmap_mode: CosHead
  head_novel_heatmap_mode: AdaptiveCosHead

training:
  batch_size: 64
  num_workers: 1
  pin_memory: True
  drop_last: False
  base:
    lr: 0.001
    epochs: 100
  novel:
    lr: 0.0001
    epochs: 50
  save_weights_path: ../data/test_weights.pt

# Dataset parameters
data:
  gen_random_seed: null                 # Can be a null, a number or a list. It's used to force the dataset generator
                                        # to recreate specific novel sets. If it's a list, it's expected to be of len |K|. 

  novel_classes_to_sample: 10           # If None, the novel_class_list will be used instead.
                                        # If both are none, all novel classes will be used. 
                                        # Otherwise, the number of novel classes to sample.

  novel_classes_list: null              # If novel_classes is null, this should be a list of 
                                        # novel classes that we want to use. If both are null,
                                        # all novel classes are used

  use_fixed_sets: False                 # It's assumed that the JSON at train_annotations_path and val_annotations_path 
                                        # are the original ones. This option can be set True for efficiency: 
                                        # we can instead pass two pre-made train and validation sets + a novel train
                                        # and a novel val sets that will directly be used.

  K: 10                                 # The number of few shots for the novel classes. Can also be a list: in that case
                                        # experiments will be repeated |K| times.
  
  val_K: 20                             # The number of few shots for the novel classes in the val dataset. 
                                        # Can also be a list: in that case experiments will be repeated |K| times.

  test_K: 20                            # The number of few shots for the novel classes in the test dataset. 
                                        # Can also be a list: in that case experiments will be repeated |K| times.

paths:
  images_dir: ../data                                         # Base folder for image paths
  annotations_path: ../data/full_2017_bboxes.json             # Full path for annotations
  novel_classes_ids_path: ../data/novel_class_ids.json        # File containing pre-determined possible class IDs
  train_annotations_path: ../data/train_2017_bboxes.json      # The original training set
  val_annotations_path: ../data/val_2017_bboxes.json          # The original validation set
  test_annotations_path: ../data/test_2017_bboxes.json        # The original test set
  train_novel_annotations_path: null                          # If use_fixed_sets = True, it expects this to contain the annotation file we want to use for the novel train set
  val_novel_annotations_path: null                            # If use_fixed_sets = True, it expects this to contain the annotation file we want to use for the novel val set
  test_novel_annotations_path: null                           # If use_fixed_sets = True, it expects this to contain the annotation file we want to use for the novel test set

debug:
  debug_mode_active: True

device: cpu       # "cpu" or "cuda"